-- Supabase Database Schema for QuanLyLinhKien
-- Execute this SQL in Supabase SQL Editor

-- Enable UUID extension if needed
create extension if not exists "uuid-ossp";

-- 1. Products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  category text,
  unit text default 'cai',
  price numeric(15,2) default 0,
  quantity integer default 0,
  min_stock integer default 0,
  type text not null default 'product' check (type in ('product', 'service')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Recipients table
create table if not exists recipients (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  type text default 'other', -- technician, collaborator, supplier, other
  phone text,
  province text,
  region text,
  address text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Transactions table
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete set null,
  type text not null check (type in ('import', 'export')),
  quantity integer not null default 0,
  price numeric(15,2) default 0,
  note text,
  recipient_id bigint references recipients(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Installation Orders table
create table if not exists installation_orders (
  id bigint generated by default as identity primary key,
  code text not null unique,
  recipient_id bigint references recipients(id) on delete set null,
  order_date date not null,
  total_quantity integer default 0,
  total_value numeric(15,2) default 0,
  note text,
  created_at timestamptz default now()
);

-- 5. Installation Order Items table
create table if not exists installation_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references installation_orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  quantity integer not null default 0,
  price numeric(15,2) default 0,
  created_at timestamptz default now()
);

-- 6. Combos table
create table if not exists combos (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. Combo Items table
create table if not exists combo_items (
  id bigint generated by default as identity primary key,
  combo_id bigint references combos(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  quantity integer not null default 0,
  created_at timestamptz default now()
);

-- 8. Banking Slips table
create table if not exists banking_slips (
  id bigint generated by default as identity primary key,
  code text not null unique,
  recipient_id bigint references recipients(id) on delete set null,
  transfer_date date not null,
  amount numeric(15,2) default 0,
  image_path text, -- URL from Cloudinary
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 9. Banking Slip Orders (linking table)
create table if not exists banking_slip_orders (
  id bigint generated by default as identity primary key,
  banking_slip_id bigint references banking_slips(id) on delete cascade,
  installation_order_id bigint references installation_orders(id) on delete cascade,
  created_at timestamptz default now()
);

-- 10. Drop Stocks table
create table if not exists drop_stocks (
  id bigint generated by default as identity primary key,
  date date not null,
  note text,
  status text default 'draft', -- draft, completed
  created_at timestamptz default now()
);

-- 11. Drop Stock Orders (linking table)
create table if not exists drop_stock_orders (
  id bigint generated by default as identity primary key,
  drop_stock_id bigint references drop_stocks(id) on delete cascade,
  installation_order_id bigint references installation_orders(id) on delete cascade,
  created_at timestamptz default now()
);

-- Create indexes for better performance
create index if not exists idx_products_code on products(code);
create index if not exists idx_recipients_code on recipients(code);
create index if not exists idx_transactions_product_id on transactions(product_id);
create index if not exists idx_transactions_recipient_id on transactions(recipient_id);
create index if not exists idx_installation_orders_code on installation_orders(code);
create index if not exists idx_installation_orders_recipient_id on installation_orders(recipient_id);
create index if not exists idx_combos_code on combos(code);
create index if not exists idx_banking_slips_code on banking_slips(code);
create index if not exists idx_banking_slips_recipient_id on banking_slips(recipient_id);

-- Disable RLS for simplicity (2 users, no auth needed initially)
-- Uncomment below if you want to enable Row Level Security later
-- alter table products enable row level security;
-- alter table recipients enable row level security;
-- ... (repeat for all tables)

-- Create policy to allow all operations for anon key (simple setup for 2 users)
-- This allows the anon key to do everything (similar to current Dexie setup)
grant all on all tables in schema public to anon;
grant all on all sequences in schema public to anon;
grant all on all tables in schema public to authenticated;
grant all on all sequences in schema public to authenticated;
